name: Unzip Omkar Apps

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Extract Omkar_Apps_Repo_v3.zip
        run: |
          unzip -o Omkar_Apps_Repo_v3.zip -d .
          rm -f Omkar_Apps_Repo_v3.zip

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped Omkar Apps repo"
          git push
